import type { Mission } from "../simulation/state";

export const missions: Mission[] = [
  {
    id: "preschool-count",
    grade: "Preschool",
    world: "Counting Comet Field",
    title: "Moon Pad Repair",
    goal: "Place exactly three moon blocks on the landing pad.",
    prompt: "Count the moon blocks. Tow three to the glowing pad.",
    targetMode: "count",
    targets: [
      { id: "pad", label: "3", accepts: ["moon", "moon", "moon"], x: 0.75, y: 0.55 },
    ],
    blocks: [
      { id: "moon-1", label: "moon", kind: "moon", color: "#ffd166" },
      { id: "moon-2", label: "moon", kind: "moon", color: "#ffd166" },
      { id: "moon-3", label: "moon", kind: "moon", color: "#ffd166" },
      { id: "star-1", label: "star", kind: "star", color: "#8ecae6" },
      { id: "shape-1", label: "tri", kind: "triangle", color: "#b8f2e6" },
    ],
  },
  {
    id: "kindergarten-word",
    grade: "Kindergarten",
    world: "Letter Nebula",
    title: "Open the Cat Gate",
    goal: "Snap c-a-t together to power the space gate.",
    prompt: "Build the word cat from left to right.",
    targetMode: "sequence",
    targets: [
      { id: "c-slot", label: "1", accepts: ["c"], x: 0.62, y: 0.5 },
      { id: "a-slot", label: "2", accepts: ["a"], x: 0.74, y: 0.5 },
      { id: "t-slot", label: "3", accepts: ["t"], x: 0.86, y: 0.5 },
    ],
    blocks: [
      { id: "letter-c", label: "c", kind: "c", color: "#ffafcc" },
      { id: "letter-a", label: "a", kind: "a", color: "#bde0fe" },
      { id: "letter-t", label: "t", kind: "t", color: "#caffbf" },
      { id: "letter-s", label: "s", kind: "s", color: "#ffc8dd" },
      { id: "letter-m", label: "m", kind: "m", color: "#fdffb6" },
    ],
  },
  {
    id: "grade1-placevalue",
    grade: "Grade 1",
    world: "Problem Planet",
    title: "Build Number 34",
    goal: "Use tens and ones blocks to make 34.",
    prompt: "Tow 3 ten-rods and 4 one-cubes into the number dock.",
    targetMode: "count",
    targets: [
      { id: "tens", label: "3 tens", accepts: ["ten", "ten", "ten"], x: 0.68, y: 0.45 },
      { id: "ones", label: "4 ones", accepts: ["one", "one", "one", "one"], x: 0.82, y: 0.62 },
    ],
    blocks: [
      { id: "ten-1", label: "10", kind: "ten", color: "#9bf6ff" },
      { id: "ten-2", label: "10", kind: "ten", color: "#9bf6ff" },
      { id: "ten-3", label: "10", kind: "ten", color: "#9bf6ff" },
      { id: "ten-4", label: "10", kind: "ten", color: "#9bf6ff" },
      { id: "one-1", label: "1", kind: "one", color: "#ffd6a5" },
      { id: "one-2", label: "1", kind: "one", color: "#ffd6a5" },
      { id: "one-3", label: "1", kind: "one", color: "#ffd6a5" },
      { id: "one-4", label: "1", kind: "one", color: "#ffd6a5" },
      { id: "one-5", label: "1", kind: "one", color: "#ffd6a5" },
    ],
  },
  {
    id: "grade3-division",
    grade: "Grade 3",
    world: "Fraction Rings",
    title: "Share Energy Equally",
    goal: "Split 12 energy blocks equally among 4 ships.",
    prompt: "Each ship needs 3 energy blocks.",
    targetMode: "count",
    targets: [
      { id: "ship-a", label: "Ship A", accepts: ["energy", "energy", "energy"], x: 0.58, y: 0.34 },
      { id: "ship-b", label: "Ship B", accepts: ["energy", "energy", "energy"], x: 0.78, y: 0.34 },
      { id: "ship-c", label: "Ship C", accepts: ["energy", "energy", "energy"], x: 0.58, y: 0.66 },
      { id: "ship-d", label: "Ship D", accepts: ["energy", "energy", "energy"], x: 0.78, y: 0.66 },
    ],
    blocks: Array.from({ length: 12 }, (_, index) => ({
      id: `energy-${index + 1}`,
      label: "⚡",
      kind: "energy",
      color: "#fca311",
    })),
  },
];
